### ISSUE TITLE
Not work with  Dapper dot net 1.42.0 

### ISSUE THREAD

**Issue by OleeOlsen** [MoonStorm/Ninject.Extensions.UnitOfWork#1]
I updated today Dapper. Now i get an exception with "file not found  Dapper 1.38".

**Comment by MoonStorm** [comment]
Wrong project Ole. 

I did an upgrade of Dapper and have not experienced any issues. Make sure neither of your projects reference the old version of Dapper. Clean the solution, and also maybe consolidate the version of the  Dapper package in all the projects via the NuGet package manager. 

As a side note though, I did find that the package manager in VS2015 isn't seeing Dapper as a dependency for Dapper.FastCrud, and I've opened a ticket for this to see what they've got to say about this problem.

**Comment by MoonStorm** [comment]
In case you still couldn't solve it, open a case in the right project and link a test solution describing your problem.
